### ISSUE TITLE
Coordinate system 

### ISSUE THREAD

**Issue by amerkoleci** [rbnpontes/REngine#37]
Hi,
What coordinate system do you use?
It seams left handed, it so you need to use LeftHanded versions of Matrix4x4, for example [CreatePerspectiveFieldOfViewLeftHanded](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4.createperspectivefieldofviewlefthanded?view=net-8.0#system-numerics-matrix4x4-createperspectivefieldofviewlefthanded(system-single-system-single-system-single-system-single))

Cheers

**Comment by amerkoleci** [comment]
> Hi @amerkoleci, i never worried about about matrix orientation because i based my whole work on the urho3d math code. Thank you very much for suggesting this, i will change my Camera matrix to use this instead

You're welcome!
Do you plan to add Native AOT support as well? What platforms you'll target?

**Comment by rbnpontes** [comment]
Yes, but I still don't have much of an idea how AOT works
The platforms I want to support at this time are Steam Deck(Linux), Windows and maybe Android.
I have a goal to make at least one game in this year, and i finishing right now some optimization's and adding my game base code like Post Process. After that i will try to port my code to Android and publish to Play Store, and finally i will implement Unit Tests to code and ensure my code quality. (i think this will go in the next year 😅)

**Comment by amerkoleci** [comment]
Nice!
Coming from C++, are any features/something you miss from C++ world?

I find some libs missing in C# ecosystem, like physics, rhi, audio, image loading

**Comment by rbnpontes** [comment]
Yes, Reflection is a example. In my first trial i started with C++, but later on i change my mind to go by the C#
C# has a tons of features that make your development more easily, like Reflections, GC, Tasks and so on. You don't need to worry about Linking issues or whatever hells problem of C++,.
Obviously you have a limit to how far you can go. If i reach this limit, i will break my code into small native modules

**Comment by rbnpontes** [comment]
Hi @amerkoleci, i made this changes and now i close this Issue.
Thanks Again for your contribution, and feel free to open whatever issue you want 😁
